name: template_app 
description: HelloWorld.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  flutx:
    path: flutx


  # getX
  get: ^4.6.1
  


  # Base Dependencies
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0

  # Icons
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1

  shimmer: ^2.0.0
  intl: ^0.17.0
  rive: ^0.8.1
  flare_flutter: ^3.0.2
  flutter_intro: ^2.3.1
  flutter_easyloading: ^3.0.3
  flutter_launcher_icons: ^0.9.2
  flutter_html: ^0.11.1
  share_plus: ^4.0.4
  flutter_cached_pdfview: ^0.4.1
  external_app_launcher: ^2.0.2
  permission_handler: ^10.0.0
  file_picker: ^4.6.1
  external_path: ^1.0.1
  dio: ^4.0.6
  flutter_local_notifications: ^9.5.3+1
  open_file: ^3.2.1
  qrscan: ^0.3.2
  badges: ^2.0.3
  pin_code_fields: ^7.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  vibration: ^1.7.6
  firebase_core: ^1.24.0
  firebase_auth: ^3.4.2
  google_sign_in: ^5.4.2
  wifi_iot: ^0.3.17
  wifi_scan: ^0.4.0+1
  wifi_connector: ^2.0.0
  mqtt_client: ^9.6.8
  device_info_plus: ^4.0.0
  network_info_plus: ^3.0.1
  modal_bottom_sheet: ^2.1.2
  slide_to_confirm: ^1.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter_icons:
#   image_path: "assets/img/login-icon-smile-launcher.png" 
#   android: true
#   ios: true

  flutter_lints: ^1.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
  #   - assets/brand/
  #   - assets/profile/
  #   - assets/img/




